version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fantasyoth
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/pg-init:/docker-entrypoint-initdb.d
      - postgres-data-fantasyoth:/var/lib/postgresql/data

volumes:
  postgres-data-fantasyoth: